services:
  windowsservice:
    image: ${DOCKER_REGISTRY-}windowsservice
    build:
      context: .
      dockerfile: WindowsService/Dockerfile

    environment:
       RABBITMQ_HOST: rabbitmq  

    depends_on:
     - rabbitmq
     

  rabbitmq:
    image: "rabbitmq:management"
    container_name: rabbitmq
    ports:
      - "15672:15672"  
      - "5672:5672"   